PImage LoadingYellow;
PImage characterMain;
PImage characterMainRev;
PImage backgroundClo2;
PImage background5;
PImage shaman;
PImage frontpage_forrest, Controls;
PImage Enter, EnterWhite, Exit, ExitWhite;
PImage End2;
PImage End2bad;
PImage GoodEndFinal;
PImage BadEnd; 
PImage BossOffice;
PImage BossOfficeGoodEnd;
PImage BadEnd1;
PImage mediumend1;
PImage MediumEndfinal;
PImage Forrest2Sky;
